package main

import (
	"log"
	"net/http"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	// generated by protoc-gen-go
	"go.sazak.io/proxyqueue/gen/proxyqueue/v1/proxyqueuev1connect" // generated by protoc-gen-connect-go
	"go.sazak.io/proxyqueue/internal/server"
)

func main() {
	srv, err := server.New("config.json")
	if err != nil {
		log.Fatalf("Failed to create server: %s", err)
	}
	mux := http.NewServeMux()
	path, handler := proxyqueuev1connect.NewProxyQueueServiceHandler(srv)
	mux.Handle(path, handler)
	http.ListenAndServe(
		"localhost:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
